config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
   
  root 'welcome#index'

  resources :categories
  resources :products
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :categoryname, presence: true,
                    length: { minimum: 5 }

    has_many :products

    
   
end

app/models/product.rb
class Product < ApplicationRecord
	validates :code, presence: true
    validates :product_name, presence: true, length: {minimum: 4}
    validates :unit_price, presence: true
    validates :sku, presence: true

    belongs_to :category
    def self.search(search)
    	if search
    		Product.where("product_name ILIKE ? OR code ILIKE ?", "%#{search}%", "%#{search}%")
    	else
    		Product.all.order("updated_at DESC").limit(10)
    	end
    end

end

app/models/supplier.rb
class Supplier < ApplicationRecord

	validates :firstname, presence: true, length: {minimum: 3}
	validates :lastname, presence: true, length: {minimum: 3}
	validates :phone, presence: true, length: {is: 10}, :uniqueness => true
	validates :address, presence: true, length: {minimum: 30}
	def self.search(search)
    	if search
    		Supplier.where("lastname ILIKE ? OR firstname ILIKE ?", "%#{search}%", "%#{search}%")
    	else
    		Supplier.all.order("updated_at DESC").limit(5)
    	end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   def find_category(catid)

        Category.find(catid).categoryname
    end
    helper_method :find_category
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
    	@category = Category.all.order("updated_at DESC")
    end

	def new
		@category = Category.new
	end
    
    def edit
	@category = Category.find(params[:id])

	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to @category
		else
			render 'new'
		end
	end

	
    def show
       @category = Category.find(params[:id])
    end

    def update
		@category = Category.find(params[:id])

		if @category.update(category_params)
			flash[:success] = "Customer was successfully updated."
			redirect_to categories_path
		else
			render 'edit'
		end
	end
    
    def destroy
    	@category = Category.find(params[:id])
        @category.destroy
 
         redirect_to categories_path
    end

	private

	def category_params
		params.require(:category).permit(:categoryname)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@product = Product.search(params[:search])

	end
    
    def new
    	@product = Product.new
    end

    def edit
    	@product = Product.find(params[:id])
    end

    def create
    	@product = Product.new(product_params)
    	if @product.save
    		redirect_to @product
    	else
    		render 'new'
    	end
    end

    def show
    	@product = Product.find(params[:id])
    end

    def update
		@product = Product.find(params[:id])

		if @product.update(product_params)
			flash[:success] = "Customer was successfully updated."
			redirect_to products_path
		else
			render 'edit'
		end
	end
    
    def destroy
    	@product = Category.find(params[:id])
        @product.destroy
 
         redirect_to products_path
    end
    
    
    private

    def product_params
    	params.require(:product).permit(:code,:product_name,:unit_price,:sku,:category_id,:product_category)
    end

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
	def index
    	@supplier = Supplier.search(params[:search])
    end

    def show
    	@supplier = Supplier.find(params[:id])
    end

	def new
		@supplier = Supplier.new
	end

	def edit
		@supplier = Supplier.find(params[:id])
	end

	def create
		@supplier = Supplier.new(supplier_params)

		if @supplier.save
			flash[:success] = "Customer was successfully created."
			redirect_to suppliers_path
		else
			render 'new'
		end
	end

	def update
		@supplier = Supplier.find(params[:id])

		if @supplier.update(customer_params)
			flash[:success] = "Customer was successfully updated."
			redirect_to suppliers_path
		else
			render 'edit'
		end
	end
    
    def destroy
    	@supplier = Supplier.find(params[:id])
    	@supplier.destroy
        flash[:danger] = "Customer was deleted successfully."
    	redirect_to suppliers_path
    end

	private

	def supplier_params
		params.require(:supplier).permit(:firstname,:lastname,:phone,:address)  
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def currency(price)
		number_to_currency(price, options = {:unit => '₹'})
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<div class = 'row'>
  <div class = 'col-xs-12'>
      <%= form_for(@category, local: true, :html => {class: "form-horizontal", role: "form"}) do |form| %>

      <div class = "form-group">
        <div class = "control-label col-sm-2">
          <%= form.label :Category %>
        </div>
        <div class = "row">
        <div class = "col-md-4">
           <%= form.text_field :categoryname, class: "form-control", placeholder: "Category Name", autofocus: true %>
        </div>
        <div class = "col-md-4">
            <%= form.submit class: 'btn btn-primary btn-md' %>
          </div>
        </div>
        </div>
      </div>
 
<% end %>
</div>
</div>

app/views/categories/edit.html.erb
<div class = "container">
	<div class = "col-sm-offset-2">
		<h1>Edit Category</h1>
	</div>
 
<%= render 'form' %>

<div class = "col-sm-offset-2"> 
<%= link_to 'Back', categories_path, class: 'btn btn-warning btn-sm' %>
</div>
</div>

app/views/categories/index.html.erb
<div class = "container">

<h1>Categories</h1>

<%= link_to 'New Category', new_category_path,class: 'btn btn-info btn-lg' %>
<p><br></p>
	
<table class = "table">
	<thead>
	<tr>
		<th>Category Name</th>
		<th colspan="3"></th>
	</tr>
</thead>

<% @category.each do |cat| %>
<tr>
	<td><%= cat.categoryname %></td>
	<td><%= link_to 'Show', category_path(cat),class: 'btn btn-info btn-sm' %></td>
	<td><%= link_to 'Edit', edit_category_path(cat),class: 'btn btn-success btn-sm' %></td>
	<td><%= link_to 'Destroy', category_path(cat), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger btn-sm' %></td>
</tr>
<% end %>
</table>
</div>

app/views/categories/new.html.erb
<div class = "conatiner">
	<div class = "col-sm-offset-2">
		<h1> Add new Category</h1>
	</div>
	<p><br></p>
	<%= render 'form' %>
	<div class = 'col-sm-offset-2'>
 	<%= link_to 'Back', categories_path,class: 'btn btn-warning btn-sm'  %>
 </div>
 </div>

app/views/categories/show.html.erb
<p>
  <strong>Category Name:</strong>
  <%= @category.categoryname %>
</p>
 <%= link_to 'Back', categories_path, class: 'btn btn-warning btn-sm' %>

app/views/layouts/_footer.html.erb
<div class = "container">
	<footer class = "footer">
		<small class = "copyright">
			Copyright &copy; <strong>Supermarket</strong> 2017 
		</small>
		<small class ="developed">
			Developed By <strong>Shubham Uttarwar</strong>
		</small>
	</footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/welcome/index">SuperMarket</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/suppliers">Suppliers</a></li>
        <li><a href="/categories">Categories <span class="sr-only">(current)</span></a></li>
        <li><a href="/products">Products</a></li>
        <li><a href="#">Sales</a></li>
        <li><a href="#">Create Order</a></li>

      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billingsystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class = "container">
    	<%= yield %>
    	<%= render 'layouts/footer'%>
    </div>

  </body>
</html>

app/views/products/_form.html.erb
<div class = "container">
<div class = "row">
  <div class = "col-xs-12">
<%= form_with model: @product, local: true, :html => {class: "form-horizontal", role: "form"} do |form| %>
 
  <%= render 'shared/errors', obj: @product %>
 
 <div class = "form-group">
    <div class = "control-label col-sm-2">
    <%= form.label(:code,'Product Code') %><br>
    </div>
  <div class = "col-sm-5">
    <%= form.text_field :code,class: "form-control", placeholder: "Product Code", autofocus: true %>
  </div>
</div>
  
 <div class = "form-group">
    <div class = "control-label col-sm-2">
      <%= form.label(:category,"Product Category") %><br>
    </div>
    <div class = "col-sm-5">
      <%= form.collection_select(:category_id, Category.all, :id, :categoryname, { :prompt => 'Select a Category', :selected => @product.category_id }) %>
    </div>
  </div>
  <div class = "form-group">
    <div class = "control-label col-sm-2">
      <%= form.label(:Product,"Product Name") %><br>
    </div>
    <div class = "col-sm-5">
      <%= form.text_field :product_name,class: "form-control", placeholder: "Product Name"%>
    </div>
  </div>
  <div class = "form-group">
    <div class = "control-label col-sm-2">
      <%= form.label(:price_per_unit,"Unit Price") %><br>
    </div>
     <div class = "col-sm-3">
      <div class = "input-group">
        <div class = "input-group-addon">₹</div>
          <%= form.text_field :unit_price,class: "form-control", placeholder: "Price Per Unit" %>
        <div class = "input-group-addon">.00</div>
      </div>
    </div>
    </div>
  <div class = "form-group">
    <div class = "control-label col-sm-2">
      <%= form.label(:sku,"SKU") %><br>
    </div>
    <div class = "col-sm-5">
      <%= form.text_field :sku,class: "form-control", placeholder: "Amount in Stock" %>
    </div>
  </div>
  <div class = "form-group">
    <div class = "col-sm-offset-2 col-sm-10">
    <%= form.submit class: 'btn btn-primary btn-lg' %>
  </div>
</div>
</div>
</div>
</div>
 
<% end %>

app/views/products/edit.html.erb
<div class = "container">
	<div class = "col-sm-offset-2">
		<h1>Edit Product</h1>
	</div>
 
<%= render 'form' %>
<div class = "col-sm-offset-2"> 
	<%= link_to 'Back', products_path, class: 'btn btn-warning btn-sm' %>
</div>
</div>

app/views/products/index.html.erb
<div class = "container">

<h1>Products</h1>

<%= link_to 'New Product', new_product_path,class: 'btn btn-info btn-lg' %>
<p><br></p>

<%= form_tag products_path, :method => 'get' do %>
	    <div class = "form-group">
	    	<div class = "control-label col-sm-4">
	       		<%= text_field_tag :search, params[:search], placeholder: "Search By Product Name or by Code", class: "form-control" %>
	       	</div>
		<div class = "form-group">
	       			<%= submit_tag "Search" ,:name => nil, class: 'btn btn-primary' %>
	       	</div>
	     </div>
    <% end %>
	
<table class = "table">
	<thead>
	<tr>
		<th>Product Code</th>
		<th>Product Category</th>
		<th>Product Name</th>
		<th>Price Per Unit</th>
		<th>SKU</th>
		<th colspan="3"></th>
	</tr>
</thead>

<% @product.each do |cat| %>
<tr>
	<td><%= cat.code %></td>
	<td><%= cat.category.categoryname %></td>
	<td><%= cat.product_name %></td>
	<td><%= currency(cat.unit_price) %></td>
	<td><%= cat.sku %></td>
	<td><%= link_to 'Show', product_path(cat),class: 'btn btn-info btn-md' %></td>
	<td><%= link_to 'Edit', edit_product_path(cat),class: 'btn btn-success btn-md' %></td>
	<td><%= link_to 'Destroy', product_path(cat), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger btn-md' %></td>
</tr>
<% end %>
</table>
</div>

app/views/products/new.html.erb
<div class ="container">
	<div class = "col-sm-offset-2">
		<h1> Add new Product</h1>
	</div>

<%= render 'form' %>

<div class = "col-sm-offset-2">
 	<%= link_to 'Back', products_path, class: 'btn btn-warning btn-sm' %>
 </div>
</div>

app/views/products/show.html.erb
<p>
  <strong>Product Code:</strong>
  <%= @product.code %>
</p>
<p>
	<strong>Product Category:</strong>
	<%= @product.category.categoryname %>
</p>
<p>
  <strong>Product Name:</strong>
  <%= @product.product_name %>
</p>
<p>
  <strong>Price Per Unit:</strong>
  <%= currency(@product.unit_price)	 %>
</p>
<p>
  <strong>SKU:</strong>
  <%= @product.sku %>
</p>
 <%= link_to 'Back', products_path,class: 'btn btn-warning btn-sm' %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class = "row">
  <div class = "col-xs-8 col-xs-offset-2">
        <div class = "panel panel-danger">
          <a herf ="#" class = "close" data-dismiss = "alert">&#215;</a>
          <div class = "panel-heading">
            <h2 class = "panel-title">
              <%= pluralize(obj.errors.count, "error") %>
            prohibited this object from beign saved:</h2>
            <div class ="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
<% end %>

app/views/suppliers/_form.html.erb
<%= render 'shared/errors', obj: @supplier %>
<div class = 'row'>
  <div class = 'col-xs-12'>
      <%= form_for(@supplier, local: true, :html => {class: "form-horizontal", role: "form"}) do |form| %>

      <div class = "form-group">
        <div class = "control-label col-sm-2">
          <%= form.label :FirstName %>
        </div>
        <div class = "col-sm-6">
           <%= form.text_field :firstname, class: "form-control", placeholder: "First Name", autofocus: true %>
        </div>
      </div>

      <div class = "form-group">
        <div class = "col-sm-2 control-label">
          <%= form.label :lastname %>
        </div>
        <div class = "col-sm-6">
           <%= form.text_field :lastname, class: "form-control", placeholder: "Last Name", autofocus: true %>
        </div>
      </div>
      
      <div class = "form-group">
        <div class = "col-sm-2 control-label">
            <%= form.label :phone %>
        </div>
        <div class = "col-sm-6">
            <%= form.text_field :phone, class: "form-control", placeholder: "Enter 10 digit phone" %>
        </div>
      </div>

      <div class = "form-group">
        <div class = "col-sm-2 control-label">
            <%= form.label :address %>
        </div>
        <div class = "col-sm-6">
            <%= form.text_area :address, class: "form-control",rows: 5, placeholder: "Enter Address"  %>
        </div>
      </div>
      
      
      <div class = "form-group">
        <div class = "col-sm-offset-2 col-sm-10">
          <%= form.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
 
<% end %>
</div>
</div>

app/views/suppliers/edit.html.erb
<div class = "container">
	<div class = "col-sm-offset-2">
		<h1> Edit Supplier Info </h1>
	</div>

<%= render 'form' %>

<div class = "col-sm-offset-2"> 
<%= link_to 'Back', url_for(:back), class: 'btn btn-warning btn-sm' %>
</div>
</div>

app/views/suppliers/index.html.erb
<div class = "container">
	<h1>Suppliers</h1>
	
    <%= link_to 'Add New Supplier', new_supplier_path, class: 'btn btn-info btn-lg' %>
    <p><br></p>
    
    <%= form_tag suppliers_path, :method => 'get' do %>
	    <div class = "form-group">
	    	<div class = "control-label col-sm-4">
	       		<%= text_field_tag :search, params[:search], placeholder: "Search By Last Name Or First Name", class: "form-control" %>
	       	</div>
	       	<div class = "form-group">
	       			<%= submit_tag "Search" ,:name => nil, class: 'btn btn-primary' %>
	       	</div>
	     </div>
    <% end %>

<% if @supplier.empty? %>
<h1 align = "center"> Oops! </h1>
<h3 align = "center">Your search was aborted due to one of the following reasons.</h3>
<h4> <br>
<ul>
	<li>There are no suppliers created!</li>
	<li>The supplier you are trying to find is not in the database.</li>
</ul>
</h4><br>
 <p align = "center"><strong>Note: </strong>Please Make sure that you have typed the correct spelling.</p>
<% else %>
<table class = "table table-hover">
	<thead>
	<tr>
		<th>Name</th>
		<th>Phone</th>
		<th>Address</th>
		<th colspan = "5"></th>
	</tr>
   </thead>
	<% @supplier.each do |cs| %>
	  <tr>
	  	<td><%= cs.firstname %> <%= cs.lastname %></td>
	  	<td><%= cs.phone %></td>
	  	<td><%= cs.address %></td>
	  	<td><%= link_to 'Show', supplier_path(cs), class: 'btn btn-info btn-sm' %></td>
	  	<td><%= link_to 'Edit', edit_supplier_path(cs), class: 'btn btn-primary btn-sm' %></td>
	  	<td><%= link_to 'Destroy', supplier_path(cs),
              method: :delete,
              data: { confirm: 'Are you sure? If you Delete the customer, all its projects will also get deleted!' }, class: 'btn btn-danger btn-sm' %></td>
	  </tr>
	  <% end %>
</table>
<% end %>
</div>

app/views/suppliers/new.html.erb
<div class = "container">
	<div class = "col-sm-offset-2">
		<h1>Add new Supplier</h1>
	</div>

<%= render 'form' %>
<div class = "col-sm-offset-2">
 <%= link_to 'Back', suppliers_path,class: 'btn btn-warning btn-sm' %>
</div>
</div>

app/views/suppliers/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @supplier.firstname %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @supplier.lastname %>
</p>
<p>
  <strong>Phone Number:</strong>
  <%= @supplier.phone %>
</p>
<p>
  <strong>Address:</strong>
  <%= @supplier.address  %>
</p>
 <%= link_to 'Back', suppliers_path, class: 'btn btn-warning btn-sm' %>

app/views/welcome/index.html.erb
<div class = "container">
	<div class = "jumbotron">
		<h1 style ="color: white" class = "indexheading" align= "center">Welcome</h1>
	</div>
</div>